(()=>{
  const byId=id=>document.getElementById(id), authHeaders=()=>({'Authorization':`Bearer ${window.PROCUREFLOW_AUTH_TOKEN||''}`,'Content-Type':'application/json'});
  const state={accounts:[],filter:'all',query:''};
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const text={hi:{'Identity administration':'पहचान प्रशासन','Farmer & staff accounts':'किसान और कर्मचारी खाते','Create secure sign-in details and maintain every service account.':'सुरक्षित साइन-इन विवरण बनाएँ और सभी सेवा खातों का प्रबंधन करें।','Create account':'खाता बनाएँ','Total managed accounts':'कुल प्रबंधित खाते','Farmers':'किसान','All accounts':'सभी खाते','Search name, email or phone':'नाम, ईमेल या फोन खोजें','Account type':'खाता प्रकार','Account status':'खाते की स्थिति','Full name':'पूरा नाम','Phone number':'फोन नंबर','Village / district':'गाँव / जिला','Assigned centre':'निर्धारित केंद्र','Active':'सक्रिय','Inactive':'निष्क्रिय','Generate':'बनाएँ','Save changes':'परिवर्तन सहेजें','Edit':'संपादित करें','Delete':'हटाएँ'},mr:{'Identity administration':'ओळख प्रशासन','Farmer & staff accounts':'शेतकरी आणि कर्मचारी खाती','Create secure sign-in details and maintain every service account.':'सुरक्षित साइन-इन तपशील तयार करा आणि सर्व सेवा खाती व्यवस्थापित करा.','Create account':'खाते तयार करा','Total managed accounts':'एकूण व्यवस्थापित खाती','Farmers':'शेतकरी','All accounts':'सर्व खाती','Search name, email or phone':'नाव, ईमेल किंवा फोन शोधा','Account type':'खाते प्रकार','Account status':'खात्याची स्थिती','Full name':'पूर्ण नाव','Phone number':'फोन नंबर','Village / district':'गाव / जिल्हा','Assigned centre':'नियुक्त केंद्र','Active':'सक्रिय','Inactive':'निष्क्रिय','Generate':'तयार करा','Save changes':'बदल जतन करा','Edit':'संपादित करा','Delete':'हटवा'}};
  Object.assign(text.hi,{'Centre staff':'केंद्र कर्मचारी','Account management':'खाता प्रबंधन','Create service account':'सेवा खाता बनाएँ','Email address':'ईमेल पता','Password':'पासवर्ड','Leave blank to generate securely':'सुरक्षित रूप से बनाने के लिए खाली छोड़ें','A secure password is generated automatically when left blank.':'खाली छोड़ने पर सुरक्षित पासवर्ड अपने आप बनेगा।','Cancel':'रद्द करें','Credentials generated':'क्रेडेंशियल बनाए गए','Account is ready':'खाता तैयार है','Share these details privately. The password is displayed only now.':'ये विवरण निजी रूप से साझा करें। पासवर्ड केवल अभी दिखेगा।','Temporary password':'अस्थायी पासवर्ड','Copy credentials':'क्रेडेंशियल कॉपी करें','Done':'पूर्ण','Loading accounts…':'खाते लोड हो रहे हैं…'});
  Object.assign(text.mr,{'Centre staff':'केंद्र कर्मचारी','Account management':'खाते व्यवस्थापन','Create service account':'सेवा खाते तयार करा','Email address':'ईमेल पत्ता','Password':'पासवर्ड','Leave blank to generate securely':'सुरक्षितपणे तयार करण्यासाठी रिकामे ठेवा','A secure password is generated automatically when left blank.':'रिकामे ठेवल्यास सुरक्षित पासवर्ड आपोआप तयार होईल.','Cancel':'रद्द करा','Credentials generated':'क्रेडेन्शियल तयार झाले','Account is ready':'खाते तयार आहे','Share these details privately. The password is displayed only now.':'हे तपशील खाजगीपणे शेअर करा. पासवर्ड फक्त आता दिसेल.','Temporary password':'तात्पुरता पासवर्ड','Copy credentials':'क्रेडेन्शियल कॉपी करा','Done':'पूर्ण','Loading accounts…':'खाती लोड होत आहेत…'});
  const tr=value=>text[window.PROCUREFLOW_LANGUAGE]?.[value]||value;
  function translateSection(){if(window.PROCUREFLOW_LANGUAGE==='en')return;const section=byId('account-dialog').parentElement;const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())if(walker.currentNode.parentElement?.closest('[data-view="accounts"],#account-dialog,#credential-dialog'))nodes.push(walker.currentNode);nodes.forEach(node=>{const raw=node.nodeValue.trim(),translated=tr(raw);if(raw&&translated!==raw)node.nodeValue=node.nodeValue.replace(raw,translated)});document.querySelectorAll('[data-view="accounts"] input[placeholder],#account-dialog input[placeholder]').forEach(input=>input.placeholder=tr(input.placeholder))}
  async function request(path,options={}){const response=await fetch(path,{...options,headers:{...authHeaders(),...(options.headers||{})}}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||'Request failed');return payload}
  function filtered(){const query=state.query.toLowerCase();return state.accounts.filter(account=>(state.filter==='all'||account.role===state.filter)&&(!query||[account.full_name,account.email,account.phone,account.location].some(value=>String(value||'').toLowerCase().includes(query))))}
  function render(){byId('account-total').textContent=state.accounts.length;byId('farmer-total').textContent=state.accounts.filter(a=>a.role==='farmer').length;byId('staff-total').textContent=state.accounts.filter(a=>a.role==='staff').length;const rows=filtered();byId('account-list').innerHTML=rows.length?rows.map(account=>`<article class="account-row" data-account-id="${esc(account.id)}"><div class="account-person"><span class="account-avatar">${esc(account.full_name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase())}</span><span><strong>${esc(account.full_name)}</strong><small>${tr(account.role==='farmer'?'Farmer':'Centre staff')} · <span class="account-status ${esc(account.status)}">${tr(account.status==='active'?'Active':'Inactive')}</span></small></span></div><div class="account-contact"><strong>${esc(account.email)}</strong><small>${esc(account.phone||'No phone added')}</small></div><div class="account-location">${esc(account.location||'No location added')}</div><div class="account-actions"><button class="button outline compact" data-account-edit type="button">${tr('Edit')}</button><button class="button ghost compact danger-action" data-account-delete type="button">${tr('Delete')}</button></div></article>`).join(''):'<div class="account-empty"><strong>No accounts found</strong><p>Create a farmer or centre-staff account to get started.</p></div>'}
  async function load(){if(!window.PROCUREFLOW_AUTH_TOKEN)return;byId('account-list').innerHTML='<div class="account-empty"><strong>Loading accounts…</strong></div>';try{state.accounts=(await request('/api/accounts')).accounts;render()}catch(error){byId('account-list').innerHTML=`<div class="account-empty"><strong>${esc(error.message)}</strong><p>Sign in again and retry.</p></div>`}}
  function generatePassword(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#',bytes=crypto.getRandomValues(new Uint8Array(14));byId('account-password').value=[...bytes].map(value=>chars[value%chars.length]).join('')}
  function updateLocationLabel(){byId('account-location-label').textContent=tr(byId('account-role').value==='staff'?'Assigned centre':'Village / district')}
  function openCreate(){byId('account-form').reset();byId('account-id').value='';byId('account-status').value='active';byId('account-dialog-title').textContent='Create service account';byId('save-account').textContent=tr('Create account');byId('password-help').textContent='A secure password is generated automatically when left blank.';byId('account-error').hidden=true;updateLocationLabel();openDialog(byId('account-dialog'))}
  function openEdit(account){byId('account-id').value=account.id;byId('account-role').value=account.role;byId('account-status').value=account.status;byId('account-name').value=account.full_name;byId('account-email').value=account.email;byId('account-phone').value=account.phone;byId('account-location').value=account.location;byId('account-password').value='';byId('account-dialog-title').textContent='Edit service account';byId('save-account').textContent=tr('Save changes');byId('password-help').textContent='Leave blank to keep the current password, or enter a new one to reset it.';byId('account-error').hidden=true;updateLocationLabel();openDialog(byId('account-dialog'))}
  function showCredentials(account,password){byId('credential-email').textContent=account.email;byId('credential-password').textContent=password||'Password unchanged';openDialog(byId('credential-dialog'))}
  byId('create-account').addEventListener('click',openCreate);byId('generate-password').addEventListener('click',generatePassword);byId('account-role').addEventListener('change',updateLocationLabel);byId('account-search').addEventListener('input',event=>{state.query=event.target.value;render()});document.querySelectorAll('[data-account-filter]').forEach(button=>button.addEventListener('click',()=>{state.filter=button.dataset.accountFilter;document.querySelectorAll('[data-account-filter]').forEach(item=>item.classList.toggle('active',item===button));render()}));
  byId('account-list').addEventListener('click',async event=>{const row=event.target.closest('[data-account-id]');if(!row)return;const account=state.accounts.find(item=>item.id===row.dataset.accountId);if(event.target.closest('[data-account-edit]'))openEdit(account);if(event.target.closest('[data-account-delete]')){if(!confirm(`Delete ${account.full_name}'s account? They will no longer be able to sign in.`))return;try{await request(`/api/accounts/${encodeURIComponent(account.id)}`,{method:'DELETE'});state.accounts=state.accounts.filter(item=>item.id!==account.id);render();toast('Account deleted')}catch(error){toast(error.message)}}});
  byId('account-form').addEventListener('submit',async event=>{event.preventDefault();const id=byId('account-id').value,payload={role:byId('account-role').value,status:byId('account-status').value,full_name:byId('account-name').value.trim(),email:byId('account-email').value.trim(),phone:byId('account-phone').value.trim(),location:byId('account-location').value.trim(),password:byId('account-password').value};const error=byId('account-error'),button=byId('save-account');button.disabled=true;error.hidden=true;try{const result=await request(id?`/api/accounts/${encodeURIComponent(id)}`:'/api/accounts',{method:id?'PATCH':'POST',body:JSON.stringify(payload)});closeDialog(byId('account-dialog'));await load();if(!id||result.temporary_password)setTimeout(()=>showCredentials(result.account,result.temporary_password),120);else toast('Account details updated')}catch(failure){error.textContent=failure.message;error.hidden=false}finally{button.disabled=false}});
  byId('copy-credentials').addEventListener('click',async()=>{await navigator.clipboard.writeText(`ProcureFlow login\nEmail: ${byId('credential-email').textContent}\nPassword: ${byId('credential-password').textContent}`);toast('Credentials copied')});
  translateSection();window.addEventListener('procureflow:login',event=>{if(event.detail.role==='admin')load()});window.ProcureFlowAccounts={load};
})();
