(()=>{
const $=s=>document.querySelector(s), escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let me=null,currentConversation=null,lastInbound='',pollTimer=null,attachment=null,recorder=null,chunks=[],installPrompt=null;
const headers=(json=false)=>{const h={'X-ProcureFlow-User':me?.id||'','X-ProcureFlow-Name':me?.name||'','X-ProcureFlow-Role':me?.role||''};if(json)h['Content-Type']='application/json';return h};
async function api(url,options={}){const response=await fetch(url,{...options,headers:{...headers(options.json),...(options.headers||{})}});const data=response.headers.get('content-type')?.includes('json')?await response.json():null;if(!response.ok)throw new Error(data?.message||'Support service is temporarily unavailable');return data}
function ding(){try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=740;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.22);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.23)}catch{}}
function filePreview(file){attachment=file;$('#chat-file-name').textContent=`${file.name} · ${(file.size/1048576).toFixed(1)} MB`;$('#attachment-preview').hidden=false}
function mediaHtml(m){if(!m.media_key)return'';const attrs=`data-media-key="${escape(m.media_key)}" data-media-name="${escape(m.media_name||'attachment')}"`;if(m.media_type?.startsWith('image/'))return `<img class="chat-media" ${attrs} alt="${escape(m.media_name||'Shared photo')}">`;if(m.media_type?.startsWith('video/'))return `<video class="chat-media" ${attrs} controls preload="metadata"></video>`;if(m.media_type?.startsWith('audio/'))return `<audio class="chat-media" ${attrs} controls preload="metadata"></audio>`;return ''}
async function hydrateMedia(log){for(const el of log.querySelectorAll('[data-media-key]:not([data-loaded])')){el.dataset.loaded='true';try{const r=await fetch(`/api/chat/media/${encodeURIComponent(el.dataset.mediaKey)}`,{headers:headers()});if(!r.ok)throw new Error();el.src=URL.createObjectURL(await r.blob())}catch{el.replaceWith(Object.assign(document.createElement('small'),{textContent:'Attachment unavailable'}))}}}
function renderMessages(items){const log=$('#chat-log'),atBottom=log.scrollHeight-log.scrollTop-log.clientHeight<100;log.innerHTML=items.length?items.map(m=>{const mine=m.sender_id===me.id,canEdit=mine&&!m.deleted_at&&m.body,canDelete=!m.deleted_at&&(mine||me.role==='admin');return `<article class="bubble ${mine?'mine':''} ${m.deleted_at?'deleted':''}" data-message="${m.id}"><div class="bubble-head"><span>${escape(m.sender_name)}</span><span>${m.sender_role==='admin'?'Support':'User'}</span></div>${m.deleted_at?'<p>Message deleted</p>':`<p>${escape(m.body)}</p>${mediaHtml(m)}`}<div class="bubble-meta"><span>${new Date(m.created_at+'Z').toLocaleString([], {hour:'2-digit',minute:'2-digit'})}${m.edited_at?' · edited':''}</span><span>${mine?(m.seen_at?'Seen ✓✓':'Sent ✓'):''}</span></div>${canEdit||canDelete?`<div class="bubble-actions">${canEdit?'<button data-edit>Edit</button>':''}${canDelete?'<button data-delete>Delete</button>':''}</div>`:''}</article>`}).join(''):'<div class="chat-empty"><b>Start the conversation</b>Send a message, photo, short video or voice note to procurement support.</div>';hydrateMedia(log);if(atBottom)log.scrollTop=log.scrollHeight;log.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editMessage(b.closest('[data-message]').dataset.message,items));log.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteMessage(b.closest('[data-message]').dataset.message));const inbound=[...items].reverse().find(m=>m.sender_id!==me.id&&!m.deleted_at);if(inbound&&lastInbound&&inbound.id!==lastInbound)ding();if(inbound)lastInbound=inbound.id}
async function loadMessages(silent=false){if(!currentConversation)return;try{const data=await api(`/api/chat/messages?conversation_id=${encodeURIComponent(currentConversation)}`);renderMessages(data.messages);await api('/api/chat/read',{method:'POST',json:true,body:JSON.stringify({conversation_id:currentConversation})});if(!silent&&data.conversation){$('#chat-with').textContent=me.role==='admin'?data.conversation.participant_name:'ProcureFlow support';$('#chat-subtitle').textContent=me.role==='admin'?`${data.conversation.participant_role} · ${data.conversation.participant_id}`:'Admin team · replies appear here' }}catch(e){if(!silent)$('#chat-log').innerHTML=`<div class="chat-empty"><b>Could not load chat</b>${escape(e.message)}</div>`}}
async function loadConversations(){if(!me)return;try{const data=await api('/api/chat/conversations'),list=$('#conversation-list');list.innerHTML=data.conversations.map(c=>`<button class="conversation ${c.id===currentConversation?'active':''}" data-conversation="${escape(c.id)}"><span class="conversation-head"><b>${escape(c.participant_name)}</b>${Number(c.unread)?`<i class="unread-count">${c.unread}</i>`:''}</span><small>${escape(c.last_message||c.participant_role||'New conversation')}</small></button>`).join('');list.querySelectorAll('[data-conversation]').forEach(b=>b.onclick=()=>{currentConversation=b.dataset.conversation;loadConversations();loadMessages()});if(!currentConversation&&data.conversations[0]){currentConversation=data.conversations[0].id;loadConversations();loadMessages()}}catch(e){$('#conversation-list').innerHTML=`<p class="muted">${escape(e.message)}</p>`}}
async function sendMessage(event){event.preventDefault();const body=$('#chat-message').value.trim();if(!body&&!attachment)return;const form=new FormData();form.set('conversation_id',currentConversation);form.set('body',body);if(attachment)form.set('attachment',attachment,attachment.name);const button=$('#chat-send');button.disabled=true;button.textContent='Sending…';try{await api('/api/chat/messages',{method:'POST',body:form});$('#chat-message').value='';attachment=null;$('#chat-attachment').value='';$('#attachment-preview').hidden=true;await loadMessages()}catch(e){alert(e.message)}finally{button.disabled=false;button.textContent='Send'}}
async function editMessage(id,items){const item=items.find(x=>x.id===id),body=prompt('Edit message',item?.body||'');if(body===null)return;try{await api(`/api/chat/messages/${encodeURIComponent(id)}`,{method:'PATCH',json:true,body:JSON.stringify({body})});loadMessages()}catch(e){alert(e.message)}}
async function deleteMessage(id){if(!confirm('Delete this message? The text and attachment will no longer be available.'))return;try{await api(`/api/chat/messages/${encodeURIComponent(id)}`,{method:'DELETE'});loadMessages()}catch(e){alert(e.message)}}
async function toggleRecording(){if(recorder?.state==='recording'){recorder.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),type=MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':'';recorder=new MediaRecorder(stream,type?{mimeType:type}:undefined);chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{filePreview(new File([new Blob(chunks,{type:recorder.mimeType})],`voice-note-${Date.now()}.webm`,{type:recorder.mimeType}));stream.getTracks().forEach(t=>t.stop());$('#record-voice').classList.remove('recording');$('#record-voice').title='Record voice note'};recorder.start();$('#record-voice').classList.add('recording');$('#record-voice').title='Stop recording'}catch{alert('Microphone permission is required to record a voice note.')}}
const botAnswers=[[/token|book|slot/i,'To book a token, open Schedules, choose a centre and time, confirm your documents, then press “Confirm and book token”.'],[/queue|wait|eta|turn/i,'Your dashboard shows farmers ahead and the estimated wait. Centre staff updates each journey stage, so the ETA changes automatically.'],[/eligib|document|aadhaar|identity/i,'Keep a government photo ID, verified bank account details, and your land or tenancy record ready.'],[/miss|late|expired/i,'Open your active token and choose “I missed my slot”. ProcureFlow will offer the next available time or another centre.'],[/payment|money|msp/i,'After procurement is completed, the journey changes to Payment initiated. The notification centre then shows the latest payment update.'],[/language|hindi|marathi/i,'Use the language selector in the top bar. English, Hindi and Marathi are available.'],[/admin|human|support|chat/i,'Choose “Live admin chat” above to speak directly with the procurement support team and share media.']];
function askBot(question){const text=question.trim();if(!text)return;const log=$('#bot-log');log.insertAdjacentHTML('beforeend',`<article class="bubble mine"><p>${escape(text)}</p></article>`);const answer=(botAnswers.find(([re])=>re.test(text))||[])[1]||'I can help with token booking, eligibility, queue ETA, missed slots, payments, languages and contacting an admin.';setTimeout(()=>{log.insertAdjacentHTML('beforeend',`<article class="bubble"><div class="bubble-head"><span>ProcureBot</span><span>Automated</span></div><p>${escape(answer)}</p></article>`);log.scrollTop=log.scrollHeight},250);$('#bot-question').value='';log.scrollTop=log.scrollHeight}
function setTab(tab){document.querySelectorAll('.support-tab').forEach(b=>b.classList.toggle('active',b.dataset.supportTab===tab));$('#bot-panel').hidden=tab!=='bot';$('#live-sidebar').hidden=tab!=='live';$('#live-panel').hidden=tab!=='live';if(tab==='live'){loadConversations();loadMessages()}}
function start(user){me={...user,id:`${user.role}-${user.email}`};$('#support-role-note').textContent=me.role==='admin'?'All farmer and staff conversations':'Private conversation with the admin team';loadConversations();clearInterval(pollTimer);pollTimer=setInterval(()=>{if(!$('#app-screen').hidden&&location.hash==='#chat'){loadConversations();loadMessages(true)}},3500)}
document.querySelectorAll('.support-tab').forEach(b=>b.onclick=()=>setTab(b.dataset.supportTab));$('#chat-form').addEventListener('submit',sendMessage);$('#chat-attachment').onchange=e=>{if(e.target.files[0])filePreview(e.target.files[0])};$('#clear-attachment').onclick=()=>{attachment=null;$('#chat-attachment').value='';$('#attachment-preview').hidden=true};$('#record-voice').onclick=toggleRecording;$('#bot-form').onsubmit=e=>{e.preventDefault();askBot($('#bot-question').value)};document.querySelectorAll('[data-bot-question]').forEach(b=>b.onclick=()=>askBot(b.dataset.botQuestion));
window.addEventListener('procureflow:login',e=>start(e.detail));if(window.PROCUREFLOW_USER)start(window.PROCUREFLOW_USER);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install-app').classList.add('ready')});$('#install-app').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install-app').classList.remove('ready')}else alert('On Android Chrome, open the browser menu and choose “Install app” or “Add to Home screen”.')};if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
})();
