const accounts={farmer:{email:'farmer@demo.in',password:'Farmer@123',name:'Ramesh Patil',label:'Farmer'},staff:{email:'staff@demo.in',password:'Staff@123',name:'Sunita Deshmukh',label:'Centre staff'},admin:{email:'admin@demo.in',password:'Admin@123',name:'Amit Kulkarni',label:'Administrator'}};
const loginScreen=document.querySelector('#login-screen'),appScreen=document.querySelector('#app-screen'),loginLanguage=document.querySelector('#login-language'),loginError=document.querySelector('#login-error');
const languageSelectors=[document.querySelector('#login-language-select'),document.querySelector('#language-select')];
const uiWords={hi:{Overview:'अवलोकन',Schedules:'समय-सारणी',Messages:'संदेश',Records:'रिकॉर्ड',Accounts:'खाते','Centre queue':'केंद्र कतार',Administration:'प्रशासन','New schedule':'नई समय-सारणी',Farmer:'किसान','Centre staff':'केंद्र कर्मचारी',Administrator:'प्रशासक'},mr:{Overview:'आढावा',Schedules:'वेळापत्रक',Messages:'संदेश',Records:'नोंदी',Accounts:'खाती','Centre queue':'केंद्र रांग',Administration:'प्रशासन','New schedule':'नवे वेळापत्रक',Farmer:'शेतकरी','Centre staff':'केंद्र कर्मचारी',Administrator:'प्रशासक'}};const tr=value=>uiWords[window.PROCUREFLOW_LANGUAGE]?.[value]||value;
languageSelectors.forEach(select=>{select.value=window.PROCUREFLOW_LANGUAGE;select.addEventListener('change',()=>{localStorage.setItem('procureflow-language',select.value);location.reload()})});
const toast=message=>{const box=document.querySelector('#toast');box.textContent=message;box.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>box.hidden=true,3200)};
let activeDialog=null;
function openDialog(dialog){if(dialog.open)return;dialog.showModal();activeDialog=dialog;history.pushState({...history.state,procureflowDialog:dialog.id},'',location.href)}
function closeDialog(dialog){if(dialog?.open)dialog.close('cancel')}
document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('close',()=>{if(activeDialog===dialog)activeDialog=null;if(history.state?.procureflowDialog===dialog.id)history.back()});dialog.addEventListener('click',event=>{if(event.target===dialog)closeDialog(dialog)})});
document.querySelectorAll('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>closeDialog(button.closest('dialog'))));
window.addEventListener('popstate',()=>{if(activeDialog?.open){const dialog=activeDialog;activeDialog=null;dialog.close('cancel')}});
let currentRole=null;
function roleLinks(role){return role==='farmer'?[['overview','⌂','Overview'],['schedules','▦','Schedules'],['messages','✉','Messages'],['chat','●','Support']]:role==='staff'?[['overview','☷','Centre queue'],['messages','✉','Messages'],['chat','●','Support']]:[['overview','▥','Administration'],['accounts','♙','Accounts'],['records','≡','Records'],['new-schedule','＋','New schedule'],['messages','✉','Messages'],['chat','●','Live chat']]}
function navFor(role){const links=roleLinks(role),desktop=document.querySelector('#primary-nav'),mobile=document.querySelector('#mobile-nav');desktop.innerHTML=links.map(([target,,label])=>`<button class="nav-role" data-nav="${target}">${tr(label)}</button>`).join('');mobile.innerHTML=links.map(([target,icon,label])=>`<button data-nav="${target}"><i>${icon}</i><span>${tr(label)}</span></button>`).join('');document.querySelectorAll('[data-nav]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();showRoute(button.dataset.nav)}))}
function showRoute(route){if(!currentRole)return;if(route==='new-schedule'){openDialog(document.querySelector('#schedule-dialog'));return}const view=route==='chat'?'chat':route==='messages'?'messages':route==='records'?'records':route==='accounts'&&currentRole==='admin'?'accounts':currentRole;document.querySelectorAll('[data-view]').forEach(section=>section.hidden=section.dataset.view!==view);document.querySelectorAll('[data-nav]').forEach(link=>link.classList.toggle('active',link.dataset.nav===route||(route==='overview'&&link.dataset.nav==='overview')));if(route==='records')initializeRecords();if(route==='accounts')window.ProcureFlowAccounts?.load();if(route==='schedules')setTimeout(()=>document.querySelector('#schedules').scrollIntoView({behavior:'smooth'}),0);location.hash=route;scrollTo({top:0,behavior:'smooth'})}
function enterApp(role,accountOverride=accounts[role],token=''){currentRole=role;const fallback=accounts[role],account={...fallback,...accountOverride,label:fallback?.label||role};window.PROCUREFLOW_USER={...account,role};window.PROCUREFLOW_AUTH_TOKEN=token;localStorage.setItem('procureflow-session',JSON.stringify({role,user:account,token}));loginScreen.hidden=true;loginLanguage.hidden=true;appScreen.hidden=false;document.querySelector('#user-name').textContent=account.name;document.querySelector('#user-role').textContent=tr(account.label);document.title=`${tr(account.label)} · ProcureFlow`;navFor(role);const requested=location.hash.slice(1);showRoute(role==='admin'&&['records','accounts'].includes(requested)?requested:['messages','chat'].includes(requested)?requested:'overview');renderToken();window.dispatchEvent(new CustomEvent('procureflow:login',{detail:window.PROCUREFLOW_USER}))}
function signOut(){window.speechSynthesis?.cancel();if(window.PROCUREFLOW_AUTH_TOKEN)fetch('/api/auth/logout',{method:'POST',headers:{Authorization:`Bearer ${window.PROCUREFLOW_AUTH_TOKEN}`}}).catch(()=>{});localStorage.removeItem('procureflow-session');window.PROCUREFLOW_AUTH_TOKEN='';currentRole=null;appScreen.hidden=true;loginScreen.hidden=false;loginLanguage.hidden=false;document.querySelector('#login-form').reset();history.replaceState(null,'','#');document.title='Sign in · ProcureFlow'}
document.querySelectorAll('[data-demo]').forEach(button=>button.addEventListener('click',()=>{const account=accounts[button.dataset.demo];document.querySelector('#login-email').value=account.email;document.querySelector('#login-password').value=account.password;loginError.hidden=true}));
document.querySelector('#login-form').addEventListener('submit',async event=>{event.preventDefault();const email=document.querySelector('#login-email').value.trim().toLowerCase(),password=document.querySelector('#login-password').value,button=event.submitter;button.disabled=true;loginError.hidden=true;try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}),result=await response.json();if(!response.ok)throw new Error(result.message||'Invalid email address or password');const role=result.user.role,account={email:result.user.email,name:result.user.name,label:role==='farmer'?'Farmer':role==='staff'?'Centre staff':'Administrator'};enterApp(role,account,result.token)}catch(error){loginError.textContent=error.message;loginError.hidden=false}finally{button.disabled=false}});
document.querySelector('#sign-out').addEventListener('click',signOut);document.querySelector('[data-scroll-schedules]').addEventListener('click',()=>document.querySelector('#schedules').scrollIntoView({behavior:'smooth'}));

let selectedCentre='Baramati Procurement Centre';document.querySelectorAll('[data-select-centre]').forEach(button=>button.addEventListener('click',()=>{selectedCentre=button.dataset.selectCentre;document.querySelectorAll('.centre-card').forEach(card=>card.classList.toggle('recommended',card.dataset.centre===selectedCentre));document.querySelector('#booking-centre').value=selectedCentre;document.querySelector('#schedules').scrollIntoView({behavior:'smooth'});toast(`${selectedCentre} selected`)}));
const bookingDialog=document.querySelector('#booking-dialog');let selectedCrop='Wheat',selectedDate='08 Sep 2026';document.querySelectorAll('[data-book]').forEach(button=>button.addEventListener('click',()=>{selectedCrop=button.dataset.crop;selectedDate=button.dataset.date;selectedCentre=button.dataset.centre;document.querySelector('#booking-crop').value=selectedCrop;document.querySelector('#booking-centre').value=selectedCentre;openDialog(bookingDialog)}));
document.querySelector('#confirm-booking').addEventListener('click',event=>{const form=bookingDialog.querySelector('form');if(!form.checkValidity()){event.preventDefault();form.reportValidity();return}const saved={token:'PF-0809-01-001',crop:document.querySelector('#booking-crop').value,date:selectedDate,centre:document.querySelector('#booking-centre').value,slot:document.querySelector('#booking-slot').value,status:'gate_checkin',quantity:document.querySelector('#quantity').value,journey:2};localStorage.setItem('procureflow-token',JSON.stringify(saved));setTimeout(()=>{renderToken();toast('Token confirmed · Email notification ready')},0)});
function renderToken(){const saved=JSON.parse(localStorage.getItem('procureflow-token')||'null'),active=document.querySelector('#active-token'),journey=document.querySelector('#journey-card');if(!saved){active.className='empty-card';active.innerHTML='<span class="empty-icon">#</span><div><h2>No active token</h2><p>Choose a recommended centre and confirm eligibility.</p></div>';journey.hidden=true;document.querySelector('#active-count').textContent='0';return}journey.hidden=false;active.className='active-token';active.innerHTML=`<div><span class="eyebrow">Your next visit</span><h2>${saved.crop} · Token #18</h2><small>${saved.date} · ${saved.slot||'10:00–11:00'}<br>${saved.centre||'Baramati Procurement Centre'} · 24 km away</small></div><div class="token-wait"><small>Current position: #7</small><b>6 farmers ahead</b><span>Estimated wait: 42 minutes</span></div><div class="token-actions"><button class="button light" data-nav="messages">Track queue</button><button class="button danger-light" id="missed-slot">I missed my slot</button></div>`;document.querySelector('#active-count').textContent=saved.status==='completed'?'0':'1';active.querySelector('[data-nav]').addEventListener('click',()=>showRoute('messages'));document.querySelector('#missed-slot').addEventListener('click',()=>openDialog(document.querySelector('#recovery-dialog')));paintJourney(saved.journey??2)}
function paintJourney(index){document.querySelectorAll('.journey-step').forEach((step,i)=>{step.classList.toggle('complete',i<index);step.classList.toggle('active',i===index)});const labels=['Token booked','Arrived at centre','Waiting for weighing','Weighing in progress','Quality inspection','Procurement accepted','Payment processing','Payment completed'];document.querySelector('#journey-status').textContent=labels[Math.min(index,7)]}
document.querySelector('#rebook-token').addEventListener('click',()=>{const choice=document.querySelector('input[name="recovery"]:checked').value.split('|'),saved=JSON.parse(localStorage.getItem('procureflow-token')||'{}');Object.assign(saved,{date:'08 Sep 2026',centre:`${choice[0]} Procurement Centre`,slot:choice[1],status:'booked',journey:0});localStorage.setItem('procureflow-token',JSON.stringify(saved));setTimeout(()=>{renderToken();toast('New slot booked · Confirmation created')},0)});

const transitions=[['booked','Booked','Mark arrived',0],['arrived','Arrived','Gate check-in',1],['gate_checkin','Gate check-in','Start weighing',2],['weighing','Weighing','Quality check',3],['quality','Quality check','Approve procurement',4],['accepted','Accepted','Initiate payment',5],['payment','Payment processing','Complete payment',6],['paid','Payment completed','Done',7]];let step=Math.min(Number(localStorage.getItem('procureflow-queue-step')||2),7);function paintQueue(){const [state,label,action,journey]=transitions[step],status=document.querySelector('#demo-status'),button=document.querySelector('#advance-status');status.className=`large-status ${state}`;status.textContent=label;button.textContent=action;button.disabled=step===7;document.querySelector('#queue-wait').textContent=step<3?'42 minutes':step<5?'12 minutes':'Completed';document.querySelector('#queue-ahead').textContent=step<3?'6 farmers ahead':step<5?'At service counter':'No waiting';document.querySelector('#complete-count').textContent=step>=5?'1':'0';const saved=JSON.parse(localStorage.getItem('procureflow-token')||'null');if(saved){saved.status=state;saved.journey=journey;localStorage.setItem('procureflow-token',JSON.stringify(saved))}}
document.querySelector('#advance-status').addEventListener('click',()=>{if(step<7)step++;localStorage.setItem('procureflow-queue-step',step);paintQueue();toast(`Journey updated: ${transitions[step][1]}`)});paintQueue();

const scheduleDialog=document.querySelector('#schedule-dialog');document.querySelector('#create-demo-schedule').addEventListener('click',()=>openDialog(scheduleDialog));document.querySelector('#publish-schedule').addEventListener('click',event=>{const form=document.querySelector('#schedule-form');if(!form.checkValidity()){event.preventDefault();form.reportValidity();return}const crop=document.querySelector('#new-crop').value,date=new Date(`${document.querySelector('#new-date').value}T00:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),capacity=document.querySelector('#new-capacity').value;document.querySelector('#admin-schedules').insertAdjacentHTML('beforeend',`<tr><td data-label="Date">${date}</td><td data-label="Commodity">${crop}</td><td data-label="Centre">Shirur Procurement Centre</td><td data-label="Tokens">0 / ${capacity}</td><td data-label="Status"><span class="large-status open">Open</span></td></tr>`);document.querySelector('#schedule-count').textContent=String(Number(document.querySelector('#schedule-count').textContent)+1);setTimeout(()=>toast('Schedule published'),0)});
document.querySelector('#enable-alerts').addEventListener('click',async()=>{if(!('Notification'in window)){toast('Phone alerts are not supported on this browser');return}const result=await Notification.requestPermission();toast(result==='granted'?'Phone alerts enabled':'Alerts remain disabled')});
document.querySelector('#move-slot').addEventListener('click',()=>openDialog(document.querySelector('#recovery-dialog')));
document.querySelector('#send-sms-alert').addEventListener('click',async event=>{const button=event.currentTarget,original=button.textContent;button.disabled=true;button.textContent='Sending…';try{const response=await fetch('/api/send-sms',{method:'POST',headers:{'Content-Type':'application/json'}}),result=await response.json();if(!response.ok)throw new Error(result.message||'Delivery failed');toast(result.message)}catch(error){toast(error.message||'SMS service is temporarily unavailable')}finally{button.disabled=false;button.textContent=original}});
document.querySelector('#send-sms-alert').textContent='Send preset SMS';
const alertComposer=document.createElement('form');alertComposer.className='alert-composer';alertComposer.id='custom-alert-form';alertComposer.innerHTML='<label for="custom-alert-message"><span>Custom farmer alert</span><textarea id="custom-alert-message" maxlength="160" required>ProcureFlow: 6 farmers are ahead. Estimated wait: 42 minutes. Please keep your documents ready.</textarea></label><div class="alert-composer-actions"><button class="button primary" type="submit">Send custom alert</button><small>Hackathon demo: exact text appears in-app and as a browser notification. Real trial SMS uses Twilio\'s preset; production uses registered procurement templates.</small></div>';const messagesContent=document.querySelector('#messages-content');messagesContent.before(alertComposer);
function renderCustomAlert(message,time='Just now'){const article=document.createElement('article'),icon=document.createElement('span'),content=document.createElement('div'),headingRow=document.createElement('div'),heading=document.createElement('h3'),timestamp=document.createElement('time'),body=document.createElement('p');icon.className='notification-icon blue';icon.textContent='✦';headingRow.className='card-title-row';heading.textContent='Custom farmer alert';timestamp.textContent=time;body.textContent=message;headingRow.append(heading,timestamp);content.append(headingRow,body);article.append(icon,content);messagesContent.prepend(article)}
const savedCustomAlerts=JSON.parse(localStorage.getItem('procureflow-custom-alerts')||'[]');savedCustomAlerts.slice().reverse().forEach(alert=>renderCustomAlert(alert.message,alert.time));
alertComposer.addEventListener('submit',async event=>{event.preventDefault();const input=document.querySelector('#custom-alert-message'),message=input.value.trim();if(!message)return;const alerts=JSON.parse(localStorage.getItem('procureflow-custom-alerts')||'[]'),time=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});alerts.unshift({message,time});localStorage.setItem('procureflow-custom-alerts',JSON.stringify(alerts.slice(0,5)));renderCustomAlert(message,time);let notified=false;if('Notification'in window){let permission=Notification.permission;if(permission==='default')permission=await Notification.requestPermission();if(permission==='granted'){new Notification('ProcureFlow farmer alert',{body:message,tag:'procureflow-custom-alert'});notified=true}}toast(notified?'Custom alert sent in-app and to this device':'Custom alert sent in-app · Enable phone alerts for device notification')});

const RECORD_COUNT=100000,RECORDS_PER_PAGE=matchMedia('(max-width:900px)').matches?10:25,crops=['Wheat','Onion','Paddy','Cotton','Soybean','Maize','Tur','Gram'],centres=['Shirur','Baramati','Daund','Indapur','Junnar'],statuses=['Booked','Arrived','Quality check','Completed','Payment initiated'],firstNames=['Ramesh','Sunita','Vijay','Asha','Ganesh','Lata','Mahesh','Savita','Suresh','Meena','Anil','Kavita'],lastNames=['Patil','Jadhav','Shinde','Pawar','More','Chavan','Kadam','Gaikwad','Mane','Deshmukh'];let procurementRecords=[],filteredRecords=[],recordsPage=1,recordsReady=false;
function recordHash(index,salt){let value=Math.imul(index+1+salt,2654435761);value^=value>>>16;value=Math.imul(value,2246822507);return(value^(value>>>13))>>>0}function buildRecords(){procurementRecords=Array.from({length:RECORD_COUNT},(_,i)=>{const n=i+1,day=1+recordHash(i,11)%30;return{id:`PF26-${String(n).padStart(6,'0')}`,farmer:`${firstNames[recordHash(i,23)%firstNames.length]} ${lastNames[recordHash(i,37)%lastNames.length]}`,crop:crops[recordHash(i,41)%crops.length],centre:centres[recordHash(i,53)%centres.length],day,quantity:Math.round((10+(recordHash(i,67)%790))/10*10)/10,wait:recordHash(i,79)%121,status:statuses[recordHash(i,97)%statuses.length]}});recordsReady=true;applyRecordFilters()}
function initializeRecords(){if(recordsReady){renderRecords();return}const body=document.querySelector('#records-body');body.innerHTML='<tr><td colspan="8" class="loading-row">Preparing 100,000 records…</td></tr>';setTimeout(buildRecords,20)}
function applyRecordFilters(){const crop=document.querySelector('#filter-crop').value,centre=document.querySelector('#filter-centre').value,status=document.querySelector('#filter-status').value,sort=document.querySelector('#record-sort').value;filteredRecords=procurementRecords.filter(row=>(!crop||row.crop===crop)&&(!centre||row.centre===centre)&&(!status||row.status===status));const sorters={newest:(a,b)=>b.day-a.day||b.id.localeCompare(a.id),oldest:(a,b)=>a.day-b.day||a.id.localeCompare(b.id),crop:(a,b)=>a.crop.localeCompare(b.crop)||a.id.localeCompare(b.id),quantity:(a,b)=>b.quantity-a.quantity||a.id.localeCompare(b.id),wait:(a,b)=>a.wait-b.wait||a.id.localeCompare(b.id),centre:(a,b)=>a.centre.localeCompare(b.centre)||a.id.localeCompare(b.id)};filteredRecords.sort(sorters[sort]||sorters.newest);recordsPage=1;renderRecords()}
function renderRecords(){if(!recordsReady)return;const totalPages=Math.max(1,Math.ceil(filteredRecords.length/RECORDS_PER_PAGE));recordsPage=Math.min(Math.max(recordsPage,1),totalPages);const start=(recordsPage-1)*RECORDS_PER_PAGE,rows=filteredRecords.slice(start,start+RECORDS_PER_PAGE);document.querySelector('#records-body').innerHTML=rows.length?rows.map(row=>`<tr><td data-label="Record ID"><strong>${row.id}</strong></td><td data-label="Farmer">${row.farmer}</td><td data-label="Crop"><strong>${row.crop}</strong></td><td data-label="Centre">${row.centre}</td><td data-label="Date">${String(row.day).padStart(2,'0')} Sep 2026</td><td data-label="Quantity">${row.quantity.toFixed(1)} q</td><td data-label="Wait">${row.wait} min</td><td data-label="Status"><span class="large-status ${row.status.toLowerCase().replaceAll(' ','_')}">${row.status}</span></td></tr>`).join(''):'<tr><td colspan="8" class="loading-row">No matching records. Clear a filter to see more.</td></tr>';document.querySelector('#filtered-count').textContent=filteredRecords.length.toLocaleString('en-IN');document.querySelector('#page-label').textContent=`Page ${recordsPage.toLocaleString('en-IN')} of ${totalPages.toLocaleString('en-IN')}`;document.querySelector('#records-prev').disabled=recordsPage===1;document.querySelector('#records-next').disabled=recordsPage===totalPages;const pages=new Set([1,totalPages,recordsPage-1,recordsPage,recordsPage+1]);document.querySelector('#pagination-pages').innerHTML=[...pages].filter(p=>p>=1&&p<=totalPages).sort((a,b)=>a-b).map((p,i,arr)=>`${i&&p-arr[i-1]>1?'<i>…</i>':''}<button type="button" class="page-button ${p===recordsPage?'active':''}" data-page="${p}">${p.toLocaleString('en-IN')}</button>`).join('');document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>{recordsPage=Number(button.dataset.page);renderRecords();document.querySelector('[data-view="records"]').scrollIntoView()}))}
document.querySelectorAll('#record-filters select').forEach(select=>select.addEventListener('change',applyRecordFilters));document.querySelector('#record-filters').addEventListener('reset',()=>setTimeout(applyRecordFilters,0));document.querySelector('#records-prev').addEventListener('click',()=>{recordsPage--;renderRecords()});document.querySelector('#records-next').addEventListener('click',()=>{recordsPage++;renderRecords()});
try{const saved=JSON.parse(localStorage.getItem('procureflow-session')||'null');if(saved?.role&&saved?.user&&saved?.token)enterApp(saved.role,saved.user,saved.token)}catch{localStorage.removeItem('procureflow-session')}
