(() => {
  const dictionaries = {
    hi: {
      "ProcureFlow home":"ProcureFlow मुख्य पृष्ठ","Primary navigation":"मुख्य नेविगेशन","Language":"भाषा","Overview":"अवलोकन","Schedules":"समय-सारणी","Messages":"संदेश","Support":"सहायता","Live chat":"लाइव चैट","Centre queue":"केंद्र कतार","Administration":"प्रशासन","New schedule":"नई समय-सारणी","Sign out":"साइन आउट","Farmer":"किसान","Centre staff":"केंद्र कर्मचारी","Administrator":"प्रशासक","Farmer assistance":"किसान सहायता","Help & live support":"सहायता और लाइव समर्थन","Get an instant automated answer or speak directly with the procurement admin.":"तुरंत स्वचालित उत्तर पाएँ या खरीद प्रशासक से सीधे बात करें।","Support online":"सहायता ऑनलाइन","ProcureBot help":"ProcureBot सहायता","Live admin chat":"प्रशासक से लाइव चैट","Conversations":"बातचीत","Write a message…":"संदेश लिखें…","Send":"भेजें","Edit":"संपादित करें","Delete":"हटाएँ","Seen":"देखा गया","Install app":"ऐप इंस्टॉल करें","User manual":"उपयोगकर्ता पुस्तिका",
      "Your mandi visit,":"आपकी मंडी यात्रा,","planned before you leave.":"निकलने से पहले नियोजित।","Check procurement schedules, confirm eligibility, book a token and follow your queue from one place.":"खरीद समय-सारणी देखें, पात्रता की पुष्टि करें, टोकन बुक करें और कतार को एक ही स्थान से ट्रैक करें।","CHECK BOOK TRACK PROCURE":"जाँचें  बुक करें  ट्रैक करें  खरीद","SECURE ACCESS":"सुरक्षित प्रवेश","Sign in to continue":"आगे बढ़ने के लिए साइन इन करें","Use one of the demonstration accounts below.":"नीचे दिए गए डेमो खातों में से एक उपयोग करें।","Email address":"ईमेल पता","Password":"पासवर्ड","Enter password":"पासवर्ड दर्ज करें","Sign in":"साइन इन करें","Farmer farmer@demo.in":"किसान farmer@demo.in","Centre staff staff@demo.in":"केंद्र कर्मचारी staff@demo.in","Administrator admin@demo.in":"प्रशासक admin@demo.in",
      "FARMER DASHBOARD":"किसान डैशबोर्ड","Plan your next procurement-centre visit.":"अपनी अगली खरीद-केंद्र यात्रा की योजना बनाएँ।","Book a token":"टोकन बुक करें","No active token":"कोई सक्रिय टोकन नहीं","Choose an open schedule and confirm your eligibility to reserve a visit.":"खुली समय-सारणी चुनें और यात्रा आरक्षित करने के लिए पात्रता की पुष्टि करें।","View schedules":"समय-सारणी देखें","ACTIVE TOKEN":"सक्रिय टोकन","Active token":"सक्रिय टोकन","Commodity":"फसल","Date":"तारीख","Centre":"केंद्र","Status":"स्थिति","Track queue":"कतार ट्रैक करें","Upcoming procurement":"आगामी खरीद","Available schedules near your district":"आपके जिले के पास उपलब्ध समय-सारणी","View all →":"सभी देखें →","Time":"समय","District":"जिला","Check eligibility":"पात्रता जाँचें","Recent messages":"हाल के संदेश","Email and in-app updates":"ईमेल और ऐप अपडेट","See messages →":"संदेश देखें →","No messages yet.":"अभी कोई संदेश नहीं।",
      "OPEN PROCUREMENT":"खुली खरीद","Find a schedule":"समय-सारणी खोजें","Filter by district or commodity, then reserve a token.":"जिला या फसल के अनुसार फ़िल्टर करें, फिर टोकन आरक्षित करें।","All districts":"सभी जिले","All commodities":"सभी फसलें","Apply filters":"फ़िल्टर लागू करें","Reset":"रीसेट","Date & time":"तारीख और समय","Procurement centre":"खरीद केंद्र","Availability":"उपलब्धता","Select":"चुनें","No matching schedules are currently open.":"अभी कोई मेल खाती समय-सारणी खुली नहीं है।","Wheat":"गेहूँ","Paddy":"धान","Onion":"प्याज़","quintals":"क्विंटल","slots left":"स्थान शेष",
      "← Back to schedules":"← समय-सारणी पर वापस","ELIGIBILITY CHECK":"पात्रता जाँच","Eligibility check":"पात्रता जाँच","Confirm your details":"अपने विवरण की पुष्टि करें","These declarations are checked before a token is issued.":"टोकन जारी होने से पहले इन घोषणाओं की जाँच होती है।","Quantity to procure (quintals)":"खरीद मात्रा (क्विंटल)","Government identity is available":"सरकारी पहचान पत्र उपलब्ध है","I can show a valid identity document at the centre.":"मैं केंद्र पर वैध पहचान दस्तावेज़ दिखा सकता/सकती हूँ।","Bank account is verified":"बैंक खाता सत्यापित है","Account and IFSC details belong to the registered farmer.":"खाता और IFSC विवरण पंजीकृत किसान के हैं।","Land or tenancy record is available":"भूमि या किरायेदारी रिकॉर्ड उपलब्ध है","I have supporting cultivation/tenancy documentation.":"मेरे पास खेती/किरायेदारी के सहायक दस्तावेज़ हैं।","Produce meets the declared commodity":"उपज घोषित फसल से मेल खाती है","Confirm and book token":"पुष्टि कर टोकन बुक करें","Open":"खुला","Visit details":"यात्रा विवरण","Time window":"समय अवधि","Address":"पता","Documents":"दस्तावेज़","Prototype eligibility:":"प्रोटोटाइप पात्रता:","Final acceptance remains subject to physical verification and applicable procurement rules.":"अंतिम स्वीकृति भौतिक सत्यापन और लागू खरीद नियमों पर निर्भर है।",
      "PROCUREMENT TOKEN":"खरीद टोकन","Procurement token":"खरीद टोकन","Keep this number ready at the centre.":"यह नंबर केंद्र पर तैयार रखें।","tokens ahead":"टोकन आगे","Estimated wait":"अनुमानित प्रतीक्षा","Now serving":"अब सेवा जारी","Completed":"पूर्ण","The estimate updates as centre staff progress the queue.":"केंद्र कर्मचारी के कतार आगे बढ़ाने पर अनुमान अपडेट होता है।","Token details":"टोकन विवरण","Date and time":"तारीख और समय","Queue position":"कतार स्थान","Eligible":"पात्र","Checked in":"चेक-इन","Serving":"सेवा जारी","Cancel token":"टोकन रद्द करें","Booked":"बुक किया गया","Cancelled":"रद्द","No Show":"अनुपस्थित",
      "CENTRE OPERATIONS":"केंद्र संचालन","Centre operations":"केंद्र संचालन","Today’s queues":"आज की कतारें","Check farmers in and keep each procurement line moving.":"किसानों का चेक-इन करें और प्रत्येक खरीद कतार को आगे बढ़ाएँ।","Total":"कुल","Waiting":"प्रतीक्षारत","Done":"पूर्ण","Open queue":"कतार खोलें","No active schedules":"कोई सक्रिय समय-सारणी नहीं","Your assigned centre has no upcoming queue.":"आपके केंद्र पर कोई आगामी कतार नहीं है।","← All queues":"← सभी कतारें","LIVE CENTRE QUEUE":"लाइव केंद्र कतार","Live centre queue":"लाइव केंद्र कतार","Refresh queue":"कतार रीफ़्रेश करें","Position":"स्थान","Token & farmer":"टोकन और किसान","Lot":"लॉट","Action":"कार्रवाई","Check in":"चेक-इन","No-show":"अनुपस्थित","Start":"शुरू करें","Complete":"पूर्ण करें","No action":"कोई कार्रवाई नहीं","No tokens booked for this schedule.":"इस समय-सारणी के लिए कोई टोकन बुक नहीं है।",
      "SYSTEM ADMINISTRATION":"सिस्टम प्रशासन","System administration":"सिस्टम प्रशासन","Procurement overview":"खरीद अवलोकन","Manage schedules and monitor system activity.":"समय-सारणी प्रबंधित करें और सिस्टम गतिविधि देखें।","Create schedule":"समय-सारणी बनाएँ","Registered farmers":"पंजीकृत किसान","Open schedules":"खुली समय-सारणी","Active tokens":"सक्रिय टोकन","Completed visits":"पूर्ण यात्राएँ","All schedules":"सभी समय-सारणियाँ","Capacity and booking status":"क्षमता और बुकिंग स्थिति","Tokens":"टोकन","Close":"बंद करें","Reopen":"फिर खोलें","← Administration":"← प्रशासन","SCHEDULE MANAGEMENT":"समय-सारणी प्रबंधन","Schedule management":"समय-सारणी प्रबंधन","Create procurement schedule":"खरीद समय-सारणी बनाएँ","Publish a capacity-controlled booking window.":"क्षमता-नियंत्रित बुकिंग विंडो प्रकाशित करें।","Capacity":"क्षमता","Start time":"प्रारंभ समय","End time":"समाप्ति समय","Minutes per token":"प्रति टोकन मिनट","Publish schedule":"समय-सारणी प्रकाशित करें",
      "NOTIFICATION CENTRE":"सूचना केंद्र","Notification centre":"सूचना केंद्र","Booking confirmations, reminders and queue updates.":"बुकिंग पुष्टि, रिमाइंडर और कतार अपडेट।","No messages yet":"अभी कोई संदेश नहीं","System notifications will appear here.":"सिस्टम सूचनाएँ यहाँ दिखाई देंगी।","Retry":"पुनः प्रयास","Sent":"भेजा गया","Logged":"दर्ज","Failed":"विफल"
    },
    mr: {
      "ProcureFlow home":"ProcureFlow मुख्यपृष्ठ","Primary navigation":"मुख्य नेव्हिगेशन","Language":"भाषा","Overview":"आढावा","Schedules":"वेळापत्रक","Messages":"संदेश","Support":"सहाय्य","Live chat":"थेट चॅट","Centre queue":"केंद्र रांग","Administration":"प्रशासन","New schedule":"नवे वेळापत्रक","Sign out":"साइन आउट","Farmer":"शेतकरी","Centre staff":"केंद्र कर्मचारी","Administrator":"प्रशासक","Farmer assistance":"शेतकरी सहाय्य","Help & live support":"मदत आणि थेट सहाय्य","Get an instant automated answer or speak directly with the procurement admin.":"त्वरित स्वयंचलित उत्तर मिळवा किंवा खरेदी प्रशासकाशी थेट बोला।","Support online":"सहाय्य ऑनलाइन","ProcureBot help":"ProcureBot मदत","Live admin chat":"प्रशासकाशी थेट चॅट","Conversations":"संभाषणे","Write a message…":"संदेश लिहा…","Send":"पाठवा","Edit":"संपादित करा","Delete":"हटवा","Seen":"पाहिले","Install app":"अॅप इंस्टॉल करा","User manual":"वापरकर्ता पुस्तिका",
      "Your mandi visit,":"तुमची बाजार समिती भेट,","planned before you leave.":"निघण्यापूर्वी नियोजित।","Check procurement schedules, confirm eligibility, book a token and follow your queue from one place.":"खरेदी वेळापत्रक पहा, पात्रता निश्चित करा, टोकन बुक करा आणि एकाच ठिकाणी रांग पाहा।","CHECK BOOK TRACK PROCURE":"तपासा  बुक करा  मागोवा  खरेदी","SECURE ACCESS":"सुरक्षित प्रवेश","Sign in to continue":"पुढे जाण्यासाठी साइन इन करा","Use one of the demonstration accounts below.":"खालील डेमो खात्यांपैकी एक वापरा।","Email address":"ईमेल पत्ता","Password":"पासवर्ड","Enter password":"पासवर्ड टाका","Sign in":"साइन इन करा","Farmer farmer@demo.in":"शेतकरी farmer@demo.in","Centre staff staff@demo.in":"केंद्र कर्मचारी staff@demo.in","Administrator admin@demo.in":"प्रशासक admin@demo.in",
      "FARMER DASHBOARD":"शेतकरी डॅशबोर्ड","Plan your next procurement-centre visit.":"तुमच्या पुढील खरेदी-केंद्र भेटीचे नियोजन करा।","Book a token":"टोकन बुक करा","No active token":"सक्रिय टोकन नाही","Choose an open schedule and confirm your eligibility to reserve a visit.":"खुले वेळापत्रक निवडा आणि भेट आरक्षित करण्यासाठी पात्रता निश्चित करा।","View schedules":"वेळापत्रक पहा","ACTIVE TOKEN":"सक्रिय टोकन","Active token":"सक्रिय टोकन","Commodity":"शेतमाल","Date":"तारीख","Centre":"केंद्र","Status":"स्थिती","Track queue":"रांग पाहा","Upcoming procurement":"आगामी खरेदी","Available schedules near your district":"तुमच्या जिल्ह्याजवळील उपलब्ध वेळापत्रके","View all →":"सर्व पहा →","Time":"वेळ","District":"जिल्हा","Check eligibility":"पात्रता तपासा","Recent messages":"अलीकडील संदेश","Email and in-app updates":"ईमेल आणि अॅप अपडेट","See messages →":"संदेश पहा →","No messages yet.":"अजून संदेश नाहीत।",
      "OPEN PROCUREMENT":"खुली खरेदी","Find a schedule":"वेळापत्रक शोधा","Filter by district or commodity, then reserve a token.":"जिल्हा किंवा शेतमालानुसार फिल्टर करा, नंतर टोकन आरक्षित करा।","All districts":"सर्व जिल्हे","All commodities":"सर्व शेतमाल","Apply filters":"फिल्टर लागू करा","Reset":"रीसेट","Date & time":"तारीख आणि वेळ","Procurement centre":"खरेदी केंद्र","Availability":"उपलब्धता","Select":"निवडा","No matching schedules are currently open.":"सध्या जुळणारे वेळापत्रक खुले नाही।","Wheat":"गहू","Paddy":"धान","Onion":"कांदा","quintals":"क्विंटल","slots left":"जागा शिल्लक",
      "← Back to schedules":"← वेळापत्रकाकडे परत","ELIGIBILITY CHECK":"पात्रता तपासणी","Eligibility check":"पात्रता तपासणी","Confirm your details":"तुमच्या तपशीलांची खात्री करा","These declarations are checked before a token is issued.":"टोकन देण्यापूर्वी या घोषणांची तपासणी केली जाते।","Quantity to procure (quintals)":"खरेदीचे प्रमाण (क्विंटल)","Government identity is available":"सरकारी ओळखपत्र उपलब्ध आहे","I can show a valid identity document at the centre.":"मी केंद्रावर वैध ओळखपत्र दाखवू शकतो/शकते।","Bank account is verified":"बँक खाते सत्यापित आहे","Account and IFSC details belong to the registered farmer.":"खाते आणि IFSC तपशील नोंदणीकृत शेतकऱ्याचे आहेत।","Land or tenancy record is available":"जमीन किंवा भाडेपट्टा नोंद उपलब्ध आहे","I have supporting cultivation/tenancy documentation.":"माझ्याकडे शेती/भाडेपट्ट्याची कागदपत्रे आहेत।","Produce meets the declared commodity":"उत्पादन घोषित शेतमालाशी जुळते","Confirm and book token":"खात्री करून टोकन बुक करा","Open":"खुले","Visit details":"भेट तपशील","Time window":"वेळेची मर्यादा","Address":"पत्ता","Documents":"कागदपत्रे","Prototype eligibility:":"प्रोटोटाइप पात्रता:","Final acceptance remains subject to physical verification and applicable procurement rules.":"अंतिम स्वीकृती प्रत्यक्ष पडताळणी आणि लागू खरेदी नियमांवर अवलंबून आहे।",
      "PROCUREMENT TOKEN":"खरेदी टोकन","Procurement token":"खरेदी टोकन","Keep this number ready at the centre.":"हा क्रमांक केंद्रावर तयार ठेवा।","tokens ahead":"टोकन पुढे","Estimated wait":"अंदाजे प्रतीक्षा","Now serving":"आता सेवा सुरू","Completed":"पूर्ण","The estimate updates as centre staff progress the queue.":"केंद्र कर्मचारी रांग पुढे नेताच अंदाज अपडेट होतो।","Token details":"टोकन तपशील","Date and time":"तारीख आणि वेळ","Queue position":"रांगेतील क्रमांक","Eligible":"पात्र","Checked in":"चेक-इन","Serving":"सेवा सुरू","Cancel token":"टोकन रद्द करा","Booked":"बुक केले","Cancelled":"रद्द","No Show":"अनुपस्थित",
      "CENTRE OPERATIONS":"केंद्र संचालन","Centre operations":"केंद्र संचालन","Today’s queues":"आजच्या रांगा","Check farmers in and keep each procurement line moving.":"शेतकऱ्यांचे चेक-इन करा आणि प्रत्येक खरेदी रांग पुढे न्या।","Total":"एकूण","Waiting":"प्रतीक्षेत","Done":"पूर्ण","Open queue":"रांग उघडा","No active schedules":"सक्रिय वेळापत्रक नाही","Your assigned centre has no upcoming queue.":"तुमच्या नियुक्त केंद्रावर आगामी रांग नाही।","← All queues":"← सर्व रांगा","LIVE CENTRE QUEUE":"थेट केंद्र रांग","Live centre queue":"थेट केंद्र रांग","Refresh queue":"रांग रीफ्रेश करा","Position":"क्रमांक","Token & farmer":"टोकन आणि शेतकरी","Lot":"लॉट","Action":"कृती","Check in":"चेक-इन","No-show":"अनुपस्थित","Start":"सुरू करा","Complete":"पूर्ण करा","No action":"कृती नाही","No tokens booked for this schedule.":"या वेळापत्रकासाठी टोकन बुक नाहीत।",
      "SYSTEM ADMINISTRATION":"सिस्टम प्रशासन","System administration":"सिस्टम प्रशासन","Procurement overview":"खरेदी आढावा","Manage schedules and monitor system activity.":"वेळापत्रके व्यवस्थापित करा आणि सिस्टम क्रियाकलाप पाहा।","Create schedule":"वेळापत्रक तयार करा","Registered farmers":"नोंदणीकृत शेतकरी","Open schedules":"खुली वेळापत्रके","Active tokens":"सक्रिय टोकन","Completed visits":"पूर्ण भेटी","All schedules":"सर्व वेळापत्रके","Capacity and booking status":"क्षमता आणि बुकिंग स्थिती","Tokens":"टोकन","Close":"बंद करा","Reopen":"पुन्हा उघडा","← Administration":"← प्रशासन","SCHEDULE MANAGEMENT":"वेळापत्रक व्यवस्थापन","Schedule management":"वेळापत्रक व्यवस्थापन","Create procurement schedule":"खरेदी वेळापत्रक तयार करा","Publish a capacity-controlled booking window.":"क्षमता-नियंत्रित बुकिंग वेळ प्रकाशित करा।","Capacity":"क्षमता","Start time":"सुरुवातीची वेळ","End time":"समाप्तीची वेळ","Minutes per token":"प्रति टोकन मिनिटे","Publish schedule":"वेळापत्रक प्रकाशित करा",
      "NOTIFICATION CENTRE":"सूचना केंद्र","Notification centre":"सूचना केंद्र","Booking confirmations, reminders and queue updates.":"बुकिंग पुष्टी, स्मरणपत्रे आणि रांग अपडेट।","No messages yet":"अजून संदेश नाहीत","System notifications will appear here.":"सिस्टम सूचना येथे दिसतील।","Retry":"पुन्हा प्रयत्न","Sent":"पाठवले","Logged":"नोंदवले","Failed":"अयशस्वी"
    }
  };
  const language = window.PROCUREFLOW_LANGUAGE || "en";
  const words = dictionaries[language];
  if (!words) return;
  Object.assign(words, language === "hi" ? {
    "Check":"जाँचें", "Book":"बुक करें", "Track":"ट्रैक करें", "Procure":"खरीद", "Farmer overview":"किसान अवलोकन",
    "Government ID, bank proof, land/tenancy record":"सरकारी पहचान पत्र, बैंक प्रमाण, भूमि/किरायेदारी रिकॉर्ड",
    "Government ID, bank proof, farmer registration":"सरकारी पहचान पत्र, बैंक प्रमाण, किसान पंजीकरण",
    "Smart centre recommendation":"स्मार्ट केंद्र सुझाव","Best centre for you":"आपके लिए सबसे अच्छा केंद्र","Compared by distance, free slots and current queue.":"दूरी, खाली स्लॉट और वर्तमान कतार के आधार पर तुलना।","Recommended":"अनुशंसित","Low":"कम","Medium":"मध्यम","Busy":"व्यस्त","Choose centre":"केंद्र चुनें","Available procurement schedules":"उपलब्ध खरीद समय-सारणी","Wait":"प्रतीक्षा","Procurement journey":"खरीद यात्रा","Arrived":"पहुंचे","Weighing":"तौल","Quality check":"गुणवत्ता जाँच","Payment":"भुगतान","Farmer updates":"किसान अपडेट","Important procurement and payment messages.":"महत्वपूर्ण खरीद और भुगतान संदेश।","Enable phone alerts":"फ़ोन अलर्ट चालू करें","Slot confirmed":"स्लॉट की पुष्टि","Your turn is approaching":"आपकी बारी आने वाली है","Payment tracking":"भुगतान ट्रैकिंग","Live queue prediction":"लाइव कतार अनुमान","Estimated wait":"अनुमानित प्रतीक्षा","I missed my slot":"मेरा स्लॉट छूट गया","Missed-slot recovery":"छूटे स्लॉट की पुनः बुकिंग","Your token has expired":"आपका टोकन समाप्त हो गया","Rebook next available slot":"अगला उपलब्ध स्लॉट बुक करें"
  } : {
    "Check":"तपासा", "Book":"बुक करा", "Track":"मागोवा", "Procure":"खरेदी", "Farmer overview":"शेतकरी आढावा",
    "Government ID, bank proof, land/tenancy record":"सरकारी ओळखपत्र, बँक पुरावा, जमीन/भाडेपट्टा नोंद",
    "Government ID, bank proof, farmer registration":"सरकारी ओळखपत्र, बँक पुरावा, शेतकरी नोंदणी",
    "Smart centre recommendation":"स्मार्ट केंद्र शिफारस","Best centre for you":"तुमच्यासाठी सर्वोत्तम केंद्र","Compared by distance, free slots and current queue.":"अंतर, रिकाम्या जागा आणि सध्याच्या रांगेनुसार तुलना।","Recommended":"शिफारस केलेले","Low":"कमी","Medium":"मध्यम","Busy":"व्यस्त","Choose centre":"केंद्र निवडा","Available procurement schedules":"उपलब्ध खरेदी वेळापत्रके","Wait":"प्रतीक्षा","Procurement journey":"खरेदी प्रवास","Arrived":"पोहोचले","Weighing":"वजन","Quality check":"गुणवत्ता तपासणी","Payment":"देयक","Farmer updates":"शेतकरी सूचना","Important procurement and payment messages.":"महत्त्वाच्या खरेदी आणि देयक सूचना।","Enable phone alerts":"फोन सूचना सुरू करा","Slot confirmed":"स्लॉट निश्चित","Your turn is approaching":"तुमची पाळी जवळ आली आहे","Payment tracking":"देयक मागोवा","Live queue prediction":"थेट रांग अंदाज","Estimated wait":"अंदाजे प्रतीक्षा","I missed my slot":"माझा स्लॉट चुकला","Missed-slot recovery":"चुकलेला स्लॉट पुन्हा बुक करा","Your token has expired":"तुमचा टोकन कालबाह्य झाला","Rebook next available slot":"पुढील उपलब्ध स्लॉट बुक करा"
  });
  Object.assign(words, language === "hi" ? {
    "ProcureFlow farmer services":"ProcureFlow किसान सेवाएँ","Help: 1800-000-2026":"सहायता: 1800-000-2026","Digital Procurement Service":"डिजिटल खरीद सेवा","Today · 10:30":"आज · 10:30","2 minutes ago":"2 मिनट पहले","ProcureFlow: 6 farmers are ahead. Estimated wait: 42 minutes. Please keep your documents ready.":"ProcureFlow: 6 किसान आगे हैं। अनुमानित प्रतीक्षा: 42 मिनट। कृपया अपने दस्तावेज़ तैयार रखें।",
    "Farmer service portal":"किसान सेवा पोर्टल","Check schedules, book a verified token and follow every procurement step from one place.":"समय-सारणी देखें, सत्यापित टोकन बुक करें और खरीद के हर चरण को एक ही जगह ट्रैक करें।","Choose a demonstration account or enter its details.":"डेमो खाता चुनें या उसका विवरण दर्ज करें।","Demo service · No ChatGPT account required":"डेमो सेवा · ChatGPT खाते की आवश्यकता नहीं",
    "Farmer dashboard":"किसान डैशबोर्ड","Plan your visit and avoid unnecessary waiting.":"अपनी यात्रा की योजना बनाएँ और अनावश्यक प्रतीक्षा से बचें।","Choose a recommended centre and confirm eligibility.":"अनुशंसित केंद्र चुनें और पात्रता की पुष्टि करें।","Waiting for weighing":"तौल की प्रतीक्षा","Gate check-in":"गेट चेक-इन","Accepted":"स्वीकृत","Payment processing":"भुगतान प्रक्रिया","Payment completed":"भुगतान पूर्ण","Live status":"लाइव स्थिति","Payment status":"भुगतान स्थिति","Processing":"प्रक्रिया जारी","Bank: SBI · Transaction ID will appear after transfer.":"बैंक: SBI · हस्तांतरण के बाद लेन-देन आईडी दिखाई देगी।","Centre advisory":"केंद्र सूचना","Shirur delayed":"शिरूर में देरी","Continue waiting, move to another slot, or contact the centre.":"प्रतीक्षा जारी रखें, दूसरा स्लॉट चुनें या केंद्र से संपर्क करें।","Move slot":"स्लॉट बदलें","Contact centre":"केंद्र से संपर्क करें","Based on your location":"आपके स्थान के आधार पर","Where should you go?":"आपको कहाँ जाना चाहिए?","Rule-based comparison of travel, queue and available slots.":"यात्रा, कतार और उपलब्ध स्लॉट की नियम-आधारित तुलना।","Choose recommended centre":"अनुशंसित केंद्र चुनें","Available procurement schedules":"उपलब्ध खरीद समय-सारणी","Open booking windows near Pune.":"पुणे के पास खुली बुकिंग विंडो।","left":"शेष","travel":"यात्रा","slots":"स्लॉट","wait":"प्रतीक्षा",
    "Today’s centre load":"आज का केंद्र भार","Expected arrivals and live congestion across nearby centres.":"आस-पास के केंद्रों में अपेक्षित आगमन और लाइव भीड़।","Live":"लाइव","Low load":"कम भार","Moderate":"मध्यम","High load":"अधिक भार","arrivals":"आगमन","Live centre queue":"लाइव केंद्र कतार","Token & farmer":"टोकन और किसान","Lot":"लॉट","Action":"कार्रवाई","Check in":"चेक-इन करें","Start weighing":"तौल शुरू करें","Approve procurement":"खरीद स्वीकृत करें","Initiate payment":"भुगतान शुरू करें","Complete payment":"भुगतान पूर्ण करें","No waiting":"कोई प्रतीक्षा नहीं","At service counter":"सेवा काउंटर पर",
    "Procurement overview":"खरीद अवलोकन","Monitor capacity, congestion and service completion.":"क्षमता, भीड़ और सेवा पूर्णता की निगरानी करें।","Create schedule":"समय-सारणी बनाएँ","+86 this week":"इस सप्ताह +86","79 total slots":"कुल 79 स्लॉट","Across 3 centres":"3 केंद्रों में","Today":"आज","Centre congestion":"केंद्र भीड़","Current operational status":"वर्तमान संचालन स्थिति","All schedules":"सभी समय-सारणियाँ","Capacity and booking status":"क्षमता और बुकिंग स्थिति",
    "Procurement data":"खरीद डेटा","Records explorer":"रिकॉर्ड खोज","Search and sort 100,000 demonstration procurement records.":"1,00,000 डेमो खरीद रिकॉर्ड खोजें और क्रमबद्ध करें।","records":"रिकॉर्ड","Crop":"फसल","All crops":"सभी फसलें","All centres":"सभी केंद्र","All statuses":"सभी स्थितियाँ","Sort by":"क्रमबद्ध करें","Newest first":"नवीनतम पहले","Oldest first":"सबसे पुराने पहले","Crop A–Z":"फसल A–Z","Quantity high–low":"मात्रा अधिक से कम","Wait time low–high":"प्रतीक्षा कम से अधिक","Centre A–Z":"केंद्र A–Z","Clear":"साफ़ करें","matching records":"मेल खाते रिकॉर्ड","Record ID":"रिकॉर्ड आईडी","Quantity":"मात्रा","Previous":"पिछला","Next":"अगला","Cotton":"कपास","Soybean":"सोयाबीन","Maize":"मक्का","Tur":"तूर","Gram":"चना","Payment initiated":"भुगतान शुरू",
    "Send preset SMS":"प्रीसेट SMS भेजें","Custom farmer alert":"कस्टम किसान अलर्ट","Send custom alert":"कस्टम अलर्ट भेजें","Hackathon demo: exact text appears in-app and as a browser notification. Real trial SMS uses Twilio's preset; production uses registered procurement templates.":"हैकाथॉन डेमो: सही संदेश ऐप और ब्राउज़र सूचना में दिखता है। वास्तविक ट्रायल SMS में Twilio प्रीसेट और उत्पादन में पंजीकृत खरीद टेम्पलेट उपयोग होते हैं।","Centre delayed":"केंद्र में देरी","Live update":"लाइव अपडेट","Journey update":"यात्रा अपडेट","Your Wheat procurement slot at Baramati Centre is confirmed for 08 Sep, 10:00–11:00.":"बारामती केंद्र पर गेहूँ खरीद का आपका स्लॉट 08 सितम्बर, 10:00–11:00 के लिए पक्का है।","6 farmers ahead · Estimated wait: 42 minutes. Please keep documents ready.":"6 किसान आगे हैं · अनुमानित प्रतीक्षा: 42 मिनट। कृपया दस्तावेज़ तैयार रखें।","Shirur centre is delayed by 45 minutes. You can move to another slot.":"शिरूर केंद्र में 45 मिनट की देरी है। आप दूसरा स्लॉट चुन सकते हैं।","₹11,250 payment has been initiated. Transaction tracking is now available.":"₹11,250 का भुगतान शुरू हो गया है। लेन-देन ट्रैकिंग अब उपलब्ध है।",
    "Six-step booking":"छह-चरण बुकिंग","Book procurement token":"खरीद टोकन बुक करें","Select commodity":"फसल चुनें","Enter quantity":"मात्रा दर्ज करें","Select centre":"केंद्र चुनें","Select time slot":"समय स्लॉट चुनें","Confirm eligibility":"पात्रता की पुष्टि करें","Valid ID will be shown at the centre.":"केंद्र पर वैध पहचान पत्र दिखाया जाएगा।","Account belongs to the registered farmer.":"खाता पंजीकृत किसान का है।","Cultivation documents are available.":"खेती के दस्तावेज़ उपलब्ध हैं।","Confirm token":"टोकन की पुष्टि करें","Token":"टोकन","We noticed you missed your slot":"आपका स्लॉट छूट गया","Your 10:00–11:00 slot expired. Choose the next available option.":"आपका 10:00–11:00 स्लॉट समाप्त हो गया। अगला उपलब्ध विकल्प चुनें।","Available":"उपलब्ध","Book next available slot":"अगला उपलब्ध स्लॉट बुक करें","Keep current token":"वर्तमान टोकन रखें","Schedule management":"समय-सारणी प्रबंधन","Create procurement schedule":"खरीद समय-सारणी बनाएँ","Publish schedule":"समय-सारणी प्रकाशित करें","Cancel":"रद्द करें","Namaskar! I’m ProcureBot.":"नमस्कार! मैं ProcureBot हूँ।","I provide automated guidance for common procurement questions. No AI account is required.":"मैं सामान्य खरीद प्रश्नों के लिए स्वचालित मार्गदर्शन देता हूँ। किसी AI खाते की आवश्यकता नहीं है।","Eligibility documents":"पात्रता दस्तावेज़","Queue & ETA":"कतार और अनुमानित समय","Missed slot":"छूटा हुआ स्लॉट","Contact admin":"प्रशासक से संपर्क","Automated":"स्वचालित","Ask me about booking, eligibility, queue ETA, missed slots, payments or languages.":"बुकिंग, पात्रता, कतार समय, छूटे स्लॉट, भुगतान या भाषा के बारे में पूछें।","Ask ProcureBot":"ProcureBot से पूछें","Ask":"पूछें","Private support conversation":"निजी सहायता बातचीत","Private conversation with the admin team":"प्रशासक टीम के साथ निजी बातचीत","All farmer and staff conversations":"सभी किसान और कर्मचारी बातचीत","Loading…":"लोड हो रहा है…","Loading conversation…":"बातचीत लोड हो रही है…","Support service is temporarily unavailable":"सहायता सेवा अभी उपलब्ध नहीं है","ProcureFlow support":"ProcureFlow सहायता","Admin team · replies appear here":"प्रशासक टीम · उत्तर यहाँ दिखाई देंगे","Message":"संदेश","Photos, short videos and voice notes · maximum 12 MB":"फोटो, छोटे वीडियो और वॉइस नोट · अधिकतम 12 MB","Messages are saved securely on the service":"संदेश सेवा पर सुरक्षित रूप से सहेजे जाते हैं","Add photo, video or audio":"फोटो, वीडियो या ऑडियो जोड़ें","Record voice note":"वॉइस नोट रिकॉर्ड करें","Remove":"हटाएँ","Start the conversation":"बातचीत शुरू करें","Send a message, photo, short video or voice note to procurement support.":"खरीद सहायता को संदेश, फोटो, छोटा वीडियो या वॉइस नोट भेजें।"
  } : {
    "ProcureFlow farmer services":"ProcureFlow शेतकरी सेवा","Help: 1800-000-2026":"मदत: 1800-000-2026","Digital Procurement Service":"डिजिटल खरेदी सेवा","Today · 10:30":"आज · 10:30","2 minutes ago":"2 मिनिटांपूर्वी","ProcureFlow: 6 farmers are ahead. Estimated wait: 42 minutes. Please keep your documents ready.":"ProcureFlow: 6 शेतकरी पुढे आहेत. अंदाजे प्रतीक्षा: 42 मिनिटे. कृपया तुमची कागदपत्रे तयार ठेवा.",
    "Farmer service portal":"शेतकरी सेवा पोर्टल","Check schedules, book a verified token and follow every procurement step from one place.":"वेळापत्रक पहा, सत्यापित टोकन बुक करा आणि खरेदीचा प्रत्येक टप्पा एकाच ठिकाणी पाहा.","Choose a demonstration account or enter its details.":"डेमो खाते निवडा किंवा त्याचा तपशील भरा.","Demo service · No ChatGPT account required":"डेमो सेवा · ChatGPT खात्याची आवश्यकता नाही",
    "Farmer dashboard":"शेतकरी डॅशबोर्ड","Plan your visit and avoid unnecessary waiting.":"भेटीचे नियोजन करा आणि अनावश्यक प्रतीक्षा टाळा.","Choose a recommended centre and confirm eligibility.":"शिफारस केलेले केंद्र निवडा आणि पात्रता निश्चित करा.","Waiting for weighing":"वजनाची प्रतीक्षा","Gate check-in":"गेट चेक-इन","Accepted":"स्वीकृत","Payment processing":"देयक प्रक्रिया","Payment completed":"देयक पूर्ण","Live status":"थेट स्थिती","Payment status":"देयक स्थिती","Processing":"प्रक्रिया सुरू","Bank: SBI · Transaction ID will appear after transfer.":"बँक: SBI · हस्तांतरणानंतर व्यवहार आयडी दिसेल.","Centre advisory":"केंद्र सूचना","Shirur delayed":"शिरूरला विलंब","Continue waiting, move to another slot, or contact the centre.":"प्रतीक्षा सुरू ठेवा, दुसरा स्लॉट निवडा किंवा केंद्राशी संपर्क करा.","Move slot":"स्लॉट बदला","Contact centre":"केंद्राशी संपर्क","Based on your location":"तुमच्या स्थानानुसार","Where should you go?":"तुम्ही कुठे जावे?","Rule-based comparison of travel, queue and available slots.":"प्रवास, रांग आणि उपलब्ध स्लॉटची नियमाधारित तुलना.","Choose recommended centre":"शिफारस केलेले केंद्र निवडा","Available procurement schedules":"उपलब्ध खरेदी वेळापत्रके","Open booking windows near Pune.":"पुण्याजवळील खुल्या बुकिंग वेळा.","left":"शिल्लक","travel":"प्रवास","slots":"स्लॉट","wait":"प्रतीक्षा",
    "Today’s centre load":"आजचा केंद्र भार","Expected arrivals and live congestion across nearby centres.":"जवळच्या केंद्रांतील अपेक्षित आगमन आणि थेट गर्दी.","Live":"थेट","Low load":"कमी भार","Moderate":"मध्यम","High load":"जास्त भार","arrivals":"आगमन","Live centre queue":"थेट केंद्र रांग","Token & farmer":"टोकन आणि शेतकरी","Lot":"लॉट","Action":"कृती","Check in":"चेक-इन करा","Start weighing":"वजन सुरू करा","Approve procurement":"खरेदी मंजूर करा","Initiate payment":"देयक सुरू करा","Complete payment":"देयक पूर्ण करा","No waiting":"प्रतीक्षा नाही","At service counter":"सेवा काउंटरवर",
    "Procurement overview":"खरेदी आढावा","Monitor capacity, congestion and service completion.":"क्षमता, गर्दी आणि सेवा पूर्णतेवर लक्ष ठेवा.","Create schedule":"वेळापत्रक तयार करा","+86 this week":"या आठवड्यात +86","79 total slots":"एकूण 79 स्लॉट","Across 3 centres":"3 केंद्रांमध्ये","Today":"आज","Centre congestion":"केंद्र गर्दी","Current operational status":"सध्याची कार्यस्थिती","All schedules":"सर्व वेळापत्रके","Capacity and booking status":"क्षमता आणि बुकिंग स्थिती",
    "Procurement data":"खरेदी डेटा","Records explorer":"रेकॉर्ड शोध","Search and sort 100,000 demonstration procurement records.":"1,00,000 डेमो खरेदी रेकॉर्ड शोधा आणि क्रम लावा.","records":"रेकॉर्ड","Crop":"पीक","All crops":"सर्व पिके","All centres":"सर्व केंद्रे","All statuses":"सर्व स्थिती","Sort by":"क्रम लावा","Newest first":"नवीन आधी","Oldest first":"जुने आधी","Crop A–Z":"पीक A–Z","Quantity high–low":"प्रमाण जास्त ते कमी","Wait time low–high":"प्रतीक्षा कमी ते जास्त","Centre A–Z":"केंद्र A–Z","Clear":"साफ करा","matching records":"जुळणारे रेकॉर्ड","Record ID":"रेकॉर्ड आयडी","Quantity":"प्रमाण","Previous":"मागील","Next":"पुढील","Cotton":"कापूस","Soybean":"सोयाबीन","Maize":"मका","Tur":"तूर","Gram":"हरभरा","Payment initiated":"देयक सुरू",
    "Send preset SMS":"प्रीसेट SMS पाठवा","Custom farmer alert":"सानुकूल शेतकरी सूचना","Send custom alert":"सानुकूल सूचना पाठवा","Hackathon demo: exact text appears in-app and as a browser notification. Real trial SMS uses Twilio's preset; production uses registered procurement templates.":"हॅकाथॉन डेमो: अचूक मजकूर अॅपमध्ये आणि ब्राउझर सूचनेत दिसतो. प्रत्यक्ष ट्रायल SMS मध्ये Twilio प्रीसेट आणि उत्पादनात नोंदणीकृत खरेदी टेम्पलेट वापरले जातात.","Centre delayed":"केंद्राला विलंब","Live update":"थेट अपडेट","Journey update":"प्रवास अपडेट","Your Wheat procurement slot at Baramati Centre is confirmed for 08 Sep, 10:00–11:00.":"बारामती केंद्रावरील गहू खरेदीचा तुमचा स्लॉट 08 सप्टेंबर, 10:00–11:00 साठी निश्चित आहे.","6 farmers ahead · Estimated wait: 42 minutes. Please keep documents ready.":"6 शेतकरी पुढे आहेत · अंदाजे प्रतीक्षा: 42 मिनिटे. कृपया कागदपत्रे तयार ठेवा.","Shirur centre is delayed by 45 minutes. You can move to another slot.":"शिरूर केंद्राला 45 मिनिटांचा विलंब आहे. तुम्ही दुसरा स्लॉट निवडू शकता.","₹11,250 payment has been initiated. Transaction tracking is now available.":"₹11,250 चे देयक सुरू झाले आहे. व्यवहार मागोवा आता उपलब्ध आहे.",
    "Six-step booking":"सहा-टप्प्यांची बुकिंग","Book procurement token":"खरेदी टोकन बुक करा","Select commodity":"पीक निवडा","Enter quantity":"प्रमाण भरा","Select centre":"केंद्र निवडा","Select time slot":"वेळ स्लॉट निवडा","Confirm eligibility":"पात्रता निश्चित करा","Valid ID will be shown at the centre.":"केंद्रावर वैध ओळखपत्र दाखवले जाईल.","Account belongs to the registered farmer.":"खाते नोंदणीकृत शेतकऱ्याचे आहे.","Cultivation documents are available.":"शेतीची कागदपत्रे उपलब्ध आहेत.","Confirm token":"टोकन निश्चित करा","Token":"टोकन","We noticed you missed your slot":"तुमचा स्लॉट चुकला आहे","Your 10:00–11:00 slot expired. Choose the next available option.":"तुमचा 10:00–11:00 स्लॉट संपला. पुढील उपलब्ध पर्याय निवडा.","Available":"उपलब्ध","Book next available slot":"पुढील उपलब्ध स्लॉट बुक करा","Keep current token":"सध्याचे टोकन ठेवा","Schedule management":"वेळापत्रक व्यवस्थापन","Create procurement schedule":"खरेदी वेळापत्रक तयार करा","Publish schedule":"वेळापत्रक प्रकाशित करा","Cancel":"रद्द करा","Namaskar! I’m ProcureBot.":"नमस्कार! मी ProcureBot आहे।","I provide automated guidance for common procurement questions. No AI account is required.":"मी सामान्य खरेदी प्रश्नांसाठी स्वयंचलित मार्गदर्शन देतो। AI खात्याची आवश्यकता नाही।","Eligibility documents":"पात्रता कागदपत्रे","Queue & ETA":"रांग आणि अंदाजे वेळ","Missed slot":"चुकलेला स्लॉट","Contact admin":"प्रशासकाशी संपर्क","Automated":"स्वयंचलित","Ask me about booking, eligibility, queue ETA, missed slots, payments or languages.":"बुकिंग, पात्रता, रांग वेळ, चुकलेले स्लॉट, देयक किंवा भाषेबद्दल विचारा।","Ask ProcureBot":"ProcureBot ला विचारा","Ask":"विचारा","Private support conversation":"खाजगी सहाय्य संभाषण","Private conversation with the admin team":"प्रशासक टीमसोबत खाजगी संभाषण","All farmer and staff conversations":"सर्व शेतकरी आणि कर्मचारी संभाषणे","Loading…":"लोड होत आहे…","Loading conversation…":"संभाषण लोड होत आहे…","Support service is temporarily unavailable":"सहाय्य सेवा सध्या उपलब्ध नाही","ProcureFlow support":"ProcureFlow सहाय्य","Admin team · replies appear here":"प्रशासक टीम · उत्तरे येथे दिसतील","Message":"संदेश","Photos, short videos and voice notes · maximum 12 MB":"फोटो, लघु व्हिडिओ आणि व्हॉइस नोट · कमाल 12 MB","Messages are saved securely on the service":"संदेश सेवेत सुरक्षितपणे जतन केले जातात","Add photo, video or audio":"फोटो, व्हिडिओ किंवा ऑडिओ जोडा","Record voice note":"व्हॉइस नोट रेकॉर्ड करा","Remove":"काढा","Start the conversation":"संभाषण सुरू करा","Send a message, photo, short video or voice note to procurement support.":"खरेदी सहाय्याला संदेश, फोटो, लघु व्हिडिओ किंवा व्हॉइस नोट पाठवा।"
  });
  const caseInsensitiveWords = Object.fromEntries(Object.entries(words).map(([key, value]) => [key.toLocaleLowerCase(), value]));
  const translateValue = (value) => {
    if (!value) return value;
    const trimmed = value.trim();
    const exact = words[trimmed] || caseInsensitiveWords[trimmed.toLocaleLowerCase()];
    if (exact) return value.replace(value.trim(), exact);
    return value
      .replace(/^Namaskar, (.+)$/g, language === "hi" ? "नमस्कार, $1" : "नमस्कार, $1")
      .replace(/(Wheat|Paddy|Onion) procurement/g, (_match, crop) => `${words[crop] || crop} ${language === "hi" ? "खरीद" : "खरेदी"}`)
      .replace(/The lot is (Wheat|Paddy|Onion) and ready for inspection\./g, (_match, crop) => language === "hi" ? `लॉट ${words[crop] || crop} है और निरीक्षण के लिए तैयार है।` : `लॉट ${words[crop] || crop} आहे आणि तपासणीसाठी तयार आहे।`)
      .replace(/About (\d+) minutes/g, language === "hi" ? "लगभग $1 मिनट" : "सुमारे $1 मिनिटे")
      .replace(/(\d+) of (\d+) slots left/g, language === "hi" ? "$1 / $2 स्थान शेष" : "$1 / $2 जागा शिल्लक")
      .replace(/(\d+) left/g, language === "hi" ? "$1 शेष" : "$1 शिल्लक")
      .replace(/(\d+) farmers ahead/g, language === "hi" ? "$1 किसान आगे" : "$1 शेतकरी पुढे")
      .replace(/(\d+) farmers/g, language === "hi" ? "$1 किसान" : "$1 शेतकरी")
      .replace(/(\d+) arrivals/g, language === "hi" ? "$1 आगमन" : "$1 आगमन")
      .replace(/Average wait (.+)$/g, language === "hi" ? "औसत प्रतीक्षा $1" : "सरासरी प्रतीक्षा $1")
      .replace(/Page ([\d,]+) of ([\d,]+)/g, language === "hi" ? "पृष्ठ $1 / $2" : "पृष्ठ $1 / $2")
      .replace(/(\d+) minutes/g, language === "hi" ? "$1 मिनट" : "$1 मिनिटे")
      .replace(/Accepted range: ([\d.]+)–([\d.]+) quintals/g, language === "hi" ? "स्वीकृत सीमा: $1–$2 क्विंटल" : "मान्य मर्यादा: $1–$2 क्विंटल");
  };
  const translateTree = (root) => {
    if (root.nodeType === Node.TEXT_NODE) {
      const translated = translateValue(root.textContent);
      if (translated !== root.textContent) root.textContent = translated;
      return;
    }
    if (!(root instanceof Element) && root !== document.body) return;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        return node.parentElement && !["SCRIPT", "STYLE"].includes(node.parentElement.tagName) && node.textContent.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
      }
    });
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach((node) => {
      const translated = translateValue(node.textContent);
      if (translated !== node.textContent) node.textContent = translated;
    });
    root.querySelectorAll?.("[placeholder],[aria-label],[title]").forEach((element) => {
      ["placeholder", "aria-label", "title"].forEach((attribute) => {
        if (element.hasAttribute(attribute)) element.setAttribute(attribute, translateValue(element.getAttribute(attribute)));
      });
    });
  };
  translateTree(document.body);
  document.querySelectorAll("[placeholder],[aria-label],[title]").forEach((element) => {
    ["placeholder", "aria-label", "title"].forEach((attribute) => {
      if (element.hasAttribute(attribute)) element.setAttribute(attribute, translateValue(element.getAttribute(attribute)));
    });
  });
  new MutationObserver((mutations) => mutations.forEach((mutation) => {
    if (mutation.type === "characterData") translateTree(mutation.target);
    mutation.addedNodes.forEach(translateTree);
  })).observe(document.body, { childList: true, subtree: true, characterData: true });
  const titleParts = document.title.split(" · ");
  titleParts[0] = translateValue(titleParts[0]);
  document.title = titleParts.join(" · ");
  document.documentElement.lang = language;
})();
